### ISSUE TITLE
Broken nav + Featured Scripts and Sprites bar

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#60] opened 2015-02-19 09:31 UTC
Everything seems to have broken within the last day or two. See live version: http://opensprites.x10.mx/live/alpha/.

**Comment by DM5555** [comment] 2015-02-19 10:05
Ah

**Comment by DM5555** [comment] 2015-02-19 10:07
OOps, I was trying to get it working in localhost and the live alpha, because the directory structure is slightly different. It is being caused by multiple 404 issues, you should get the PHP guys to fix it

**Comment by DM5555** [comment] 2015-02-19 10:09
It's the header.php file, which should link to two other files, Header-Local.php and Header-AlphaLive.php, change it to header alpha live

**Comment by DM5555** [comment] 2015-02-19 10:16
It might work now, try updating it

**Comment by pilppe** [comment] 2015-02-19 10:32
It stopped working after Rumantis pull request was merged

**Comment by The-Cheese-Eater** [comment] 2015-02-19 10:44
I've updated the live server. 

I know it wasn't Rumanti's merge because I made a mistake and didn't download the updates before I FTPed the server, so it didn't upload. It was DM's file changes.

**Comment by DM5555** [comment] 2015-02-19 12:58
^

**Comment by The-Cheese-Eater** [comment] 2015-02-19 13:28
I think the Featured Scripts and Sprites bar is fixed now.

**Comment by Firedrake969** [comment] 2015-02-19 13:29
Navbar still broken

**Comment by DM5555** [comment] 2015-02-19 13:52
?

**Comment by DM5555** [comment] 2015-02-19 13:53
Have you updated it yet?

**Comment by Firedrake969** [comment] 2015-02-19 14:25
I'm doing backend PHP work (registration stuff)

**Comment by DM5555** [comment] 2015-02-19 14:40
All sorted

**Comment by Firedrake969** [comment] 2015-02-19 14:46
See my other comment on the other related issue

**Closed** 2015-02-20 18:48 UTC
Labels: bug, help wanted, high priority, ongoing
