### ISSUE TITLE
Footer on forums

### ISSUE THREAD

**Issue by JelloMonster118** [OpenSprites/OpenSprites#194] opened 2015-11-27 04:00 UTC
doesn't look very good.

**Comment by Arinerron** [comment] 2015-11-27 05:47
I've been noticing that too... I'll talk to them about it...

**Comment by Rumanti** [comment] 2015-11-27 11:27
This issue is a duplicate of an issue already created by Liam4. Sorry can not link now, got to go to 800+ km away to Yogyakarta.

**Comment by liam4** [comment] 2015-11-27 14:32
\*cough\* \*cough\* #173 :package:

**Closed by liam4** 2015-11-27 14:32 UTC
